# Base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy code and requirements
COPY requirements.txt .
COPY kafka_producer_consumer.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the app
CMD ["python", "kafka_producer_consumer.py"]