# Use a lightweight Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files into container
COPY requirements.txt .
COPY kafka_producer_consumer.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Python script
CMD ["python", "-u", "/app/kafka_producer_consumer.py"]