apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      containers:
        - name: mqtt-bridge
          image: python-bridge:v1
          imagePullPolicy: IfNotPresent
